export const IS_WALLET_SIGNED_IN = "IS_WALLET_SIGNED_IN";
export const GET_WALLET_INFO = "GET_WALLET_INFO";
export const USER_DATA = "USER_DATA";
export const SEARCH_RESULTS = "SEARCH_RESULTS";
export const HEADER_SEARCH_LOADING = "HEADER_SEARCH_LOADING";
export const SEARCH_LOADING = "SEARCH_LOADING";
export const PAGINATION = "PAGINATION";
export const ALL_NFTS = "ALL_NFTS";